In [3]:
import numpy as np

# Define matrices
A = np.array([[2, 4, 5], [1, 3, 2], [3, 6, 1]])
B = np.array([[3, 2, 1], [6, 3, 0], [5, 3, 2]])




In [4]:
#t1
sum_matrix = A + B  # 1. Compute the element-wise sum (A + B)
sum_matrix = A + B
print("Element-wise Sum:\n", sum_matrix)

# 2. Compute the element-wise product (A * B)


# 3. Compute the dot product A * B^T (B Transpose)


# 4. Compute the determinant of A

print("Element-wise Sum:\n", sum_matrix)

Element-wise Sum:
 [[5 6 6]
 [7 6 2]
 [8 9 3]]


In [5]:
#t2
product_matrix = A * B
print("\nElement-wise Product:\n", product_matrix)


Element-wise Product:
 [[ 6  8  5]
 [ 6  9  0]
 [15 18  2]]


In [6]:
#t3
dot_product = np.dot(A, B.T)
print("\nDot Product (A * B^T):\n", dot_product)


Dot Product (A * B^T):
 [[19 24 32]
 [11 15 18]
 [22 36 35]]


In [7]:
#t4
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:", det_A)


Determinant of Matrix A: -13.0
